theme: jekyll-theme-minimal
title: Shreyas
author: Shreyas
description: Personal Page
header:
  logo: /assets/img/profile.jpg
  navigation:
    - title: "Home"
      url: "/"
    - title: "Research"
      url: "/research"
    - title: "CV"
      url: "/cv"
    - title: "Projects"
      url: "/projects"
    - title: "Physics Problems"
      url: "/problems"
