theme: jekyll-theme-slate
title: "Shreyas"
author: Shreyas
description: Personal Page
header:
  logo: /assets/img/logo.png
  navigation:
    - title: "Home"
      url: "/"
    - title: "Research"
      url: "/research"
    - title: "CV"
      url: "/cv"
    - title: "Projects"
      url: "/projects"
    - title: "Physics Problems"
      url: "/problems"
